sudo: false
language: node_js
node_js:
  - '9'
  - '8'
  - '6'
  - '4'

cache:
  directories:
    - ~/.npm

notifications:
  email: false

deploy:
  provider: npm
  email: "garydouble@live.com"
  api_key: NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
