sudo: false

language: node_js
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
  
cache:
  directories:
    - ~/.npm
    
notifications:
  email: false
  
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  
branches:
  except:
    - /^[vV]?\d+\.\d+\.\d+$/
